# Configuraci칩n b치sica del sitio
title: Proyecto de NLP
description: Resultados de mi proyecto de Procesamiento de Lenguaje Natural
author: Tu Nombre

# Configuraci칩n de Jekyll
theme: jekyll-theme-minimal

# Configuraciones adicionales
show_downloads: false
google_analytics: # Tu ID de Google Analytics (opcional)

# Colecciones (si las necesitas)
# collections:
#   my_collection:
#     output: true

# Configuraciones de compilaci칩n
markdown: kramdown
highlighter: rouge

# Exclusiones
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (opcional)
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag