title: Generador de discursos TED
description: Resultados del proyecto final de la asignatura de Procesamiento de Lenguaje Natural
theme: jekyll-theme-cayman
show_downloads: false
google_analytics:
github:
  is_project_page: true
  repository_url: https://github.com/balechon/GeneradorDiscursos
  repository_name: GeneradorDiscursos
  owner_name: balechon
  owner_url: https://github.com/balechon